//! Shared helpers for the format crates' generated-fixture tests: a small
//! deterministic random generator, a mutation fuzzer and an RSC5 container
//! writer. Included by each crate's `tests/generated.rs` with
//! `#[path = "../../tests/support.rs"] mod support;`, so it needs no crate of
//! its own and pulls in no dependency.
//!
//! Nothing here comes from the game: every fixture is generated by the tests.
//!
//! # Fuzzing
//!
//! [`fuzz`] takes a set of valid seed inputs (built by the calling test),
//! applies one to four random mutations per iteration (bit flips, byte
//! overwrites, truncations, insertions, deletions, block duplication and
//! "length field" corruption: an aligned u16 or u32 overwritten with a
//! boundary value such as 0, 1, the input length, `0x7FFF_FFFF` or
//! `0xFFFF_FFFF`) and calls the parser under test on the result inside
//! `catch_unwind`. A panic fails the test and prints the iteration, the
//! seed index and the whole input as a Rust byte-array literal, ready to be
//! kept as a regression test.
//!
//! Iteration counts are small by default so that `cargo test` stays fast.
//! Two environment variables tune a longer run:
//!
//! - `LF_FUZZ_ITERS`: iterations per fuzz target (overrides the default).
//! - `LF_FUZZ_SEED`: base seed of the generator (default fixed), so a long
//!   run can explore a different sequence. A failure report names the seed.
//!
//! Example: `LF_FUZZ_ITERS=200000 cargo test -p lf-archive --test generated`.

// Each test binary uses a different subset of these helpers, and fixture
// arithmetic deliberately truncates random words to bytes and halves.
#![allow(
    dead_code,
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_lossless
)]

use std::panic::{AssertUnwindSafe, catch_unwind};

/// Environment variable overriding the number of fuzz iterations.
pub const ITERS_ENV: &str = "LF_FUZZ_ITERS";
/// Environment variable overriding the fuzzer's base seed.
pub const SEED_ENV: &str = "LF_FUZZ_SEED";
/// Base seed used when `LF_FUZZ_SEED` is not set.
pub const DEFAULT_SEED: u64 = 0x4C46_5F46_555A_5A31;

/// Magic word of a PC RSC5 resource ("RSC" + 0x05, little-endian).
pub const RSC5_MAGIC: u32 = 0x0543_5352;
/// Largest mantissa of a segment size in the RSC5 flags word (11 bits).
const RSC5_MANTISSA_MAX: usize = 0x7FF;
/// Largest data length of one stored deflate block.
const STORED_BLOCK_MAX: usize = 0xFFFF;
/// Modulus of the Adler-32 checksum that ends a zlib stream.
const ADLER_MOD: u32 = 65_521;

/// Deterministic pseudo-random generator (`SplitMix64`). Not for
/// cryptography; chosen because it is tiny, fast and has no bad seeds.
#[derive(Debug, Clone)]
pub struct Rng(u64);

impl Rng {
    /// A generator starting from `seed`.
    #[must_use]
    pub fn new(seed: u64) -> Rng {
        Rng(seed)
    }

    /// A generator for one named test: the base seed mixed with a hash of
    /// the name, so each test explores its own sequence.
    #[must_use]
    pub fn for_test(name: &str) -> Rng {
        Rng(base_seed() ^ fnv1a(name.as_bytes()))
    }

    /// Next 64 random bits.
    pub fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Next 32 random bits.
    pub fn next_u32(&mut self) -> u32 {
        (self.next_u64() >> 32) as u32
    }

    /// A value in `0..n` (`n` must be non-zero).
    pub fn below(&mut self, n: usize) -> usize {
        assert!(n > 0, "below(0)");
        (self.next_u64() % n as u64) as usize
    }

    /// A value in `lo..=hi`.
    pub fn range(&mut self, lo: usize, hi: usize) -> usize {
        lo + self.below(hi - lo + 1)
    }

    /// True with probability `num / den`.
    pub fn chance(&mut self, num: usize, den: usize) -> bool {
        self.below(den) < num
    }

    /// A finite float in `lo..hi`.
    pub fn f32_in(&mut self, lo: f32, hi: f32) -> f32 {
        let unit = (self.next_u32() >> 8) as f32 / (1u32 << 24) as f32;
        lo + (hi - lo) * unit
    }

    /// One element of a non-empty slice.
    pub fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        &items[self.below(items.len())]
    }

    /// `n` random bytes.
    pub fn bytes(&mut self, n: usize) -> Vec<u8> {
        (0..n).map(|_| self.next_u32() as u8).collect()
    }

    /// An identifier of `lo..=hi` characters: a letter, then letters,
    /// digits and underscores.
    pub fn ident(&mut self, lo: usize, hi: usize) -> String {
        const FIRST: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
        const REST: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789_";
        let len = self.range(lo.max(1), hi.max(1));
        let mut s = String::with_capacity(len);
        s.push(*self.pick(FIRST) as char);
        for _ in 1..len {
            s.push(*self.pick(REST) as char);
        }
        s
    }
}

/// 64-bit FNV-1a, used only to derive per-test seeds.
fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xCBF2_9CE4_8422_2325;
    for &b in bytes {
        h ^= u64::from(b);
        h = h.wrapping_mul(0x0000_0100_0000_01B3);
    }
    h
}

/// The base seed: `LF_FUZZ_SEED` if set (decimal or `0x` hex), else
/// [`DEFAULT_SEED`].
#[must_use]
pub fn base_seed() -> u64 {
    std::env::var(SEED_ENV)
        .ok()
        .and_then(|s| {
            let s = s.trim();
            s.strip_prefix("0x")
                .map_or_else(|| s.parse().ok(), |h| u64::from_str_radix(h, 16).ok())
        })
        .unwrap_or(DEFAULT_SEED)
}

/// Fuzz iterations to run: `LF_FUZZ_ITERS` if set, else `default`.
#[must_use]
pub fn iterations(default: usize) -> usize {
    std::env::var(ITERS_ENV)
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(default)
}

/// Boundary values written over "length fields" by the mutator.
fn interesting_u32(len: usize, rng: &mut Rng) -> u32 {
    let len = u32::try_from(len).unwrap_or(u32::MAX);
    match rng.below(12) {
        0 => 0,
        1 => 1,
        2 => len,
        3 => len.wrapping_add(1),
        4 => len.wrapping_sub(1),
        5 => 0x7FFF_FFFF,
        6 => 0xFFFF_FFFF,
        7 => 0x8000_0000,
        8 => 0xFFFF,
        9 => 0x5000_0000 | (rng.next_u32() & 0xFFFF), // a plausible tagged pointer
        10 => rng.next_u32() & 0xFF,
        _ => rng.next_u32(),
    }
}

/// Apply one random mutation to `data` in place.
pub fn mutate_once(rng: &mut Rng, data: &mut Vec<u8>) {
    if data.is_empty() {
        let n = rng.range(1, 16);
        data.extend(rng.bytes(n));
        return;
    }
    let len = data.len();
    match rng.below(10) {
        // Flip one bit.
        0 | 1 => {
            let at = rng.below(len);
            data[at] ^= 1 << rng.below(8);
        }
        // Overwrite one byte.
        2 => {
            let at = rng.below(len);
            let random = rng.next_u32() as u8;
            data[at] = *rng.pick(&[0x00, 0x01, 0x7F, 0x80, 0xFF, random]);
        }
        // Corrupt an aligned u32 "length field".
        3 | 4 if len >= 4 => {
            let at = rng.below(len / 4) * 4;
            let v = interesting_u32(len, rng);
            data[at..at + 4].copy_from_slice(&v.to_le_bytes());
        }
        // Corrupt an aligned u16.
        5 if len >= 2 => {
            let at = rng.below(len / 2) * 2;
            let v = interesting_u32(len, rng) as u16;
            data[at..at + 2].copy_from_slice(&v.to_le_bytes());
        }
        // Truncate.
        6 => {
            let keep = rng.below(len);
            data.truncate(keep);
        }
        // Insert random bytes.
        7 => {
            let at = rng.below(len + 1);
            let n = rng.range(1, 16);
            let extra = rng.bytes(n);
            data.splice(at..at, extra);
        }
        // Delete a run.
        8 => {
            let at = rng.below(len);
            let n = rng.range(1, 16).min(len - at);
            data.drain(at..at + n);
        }
        // Duplicate a block elsewhere (overwrite, keeps the length).
        _ => {
            let n = rng.range(1, 32).min(len);
            let from = rng.below(len - n + 1);
            let to = rng.below(len - n + 1);
            let block = data[from..from + n].to_vec();
            data[to..to + n].copy_from_slice(&block);
        }
    }
}

/// A mutated copy of `input`: one to four mutations.
#[must_use]
pub fn mutate(rng: &mut Rng, input: &[u8]) -> Vec<u8> {
    let mut out = input.to_vec();
    for _ in 0..rng.range(1, 4) {
        mutate_once(rng, &mut out);
    }
    out
}

/// Format `bytes` as a Rust byte-array literal (for regression tests).
#[must_use]
pub fn rust_literal(bytes: &[u8]) -> String {
    let mut s = String::from("&[");
    for (i, b) in bytes.iter().enumerate() {
        if i % 16 == 0 {
            s.push_str("\n    ");
        }
        s.push_str(&format!("0x{b:02X}, "));
    }
    s.push_str("\n]");
    s
}

/// Run `check` on `input`; a panic fails the test with a reproducible report.
pub fn assert_no_panic<F: Fn(&[u8])>(what: &str, input: &[u8], check: &F) {
    assert!(
        catch_unwind(AssertUnwindSafe(|| check(input))).is_ok(),
        "{what}: parser panicked on this input ({} bytes, base seed {:#x}):\n{}",
        input.len(),
        base_seed(),
        rust_literal(input)
    );
}

/// Mutation fuzzer: for `iterations(default_iters)` rounds, mutate one of
/// `seeds` and call `check` on the result. `check` must not panic; it is
/// expected to call the parser and may assert invariants on a successful
/// parse. The unmutated seeds and every prefix of the first seed up to 64
/// bytes are checked as well.
pub fn fuzz<F: Fn(&[u8])>(name: &str, seeds: &[Vec<u8>], default_iters: usize, check: F) {
    assert!(!seeds.is_empty(), "{name}: no seeds");
    for (i, seed) in seeds.iter().enumerate() {
        assert_no_panic(&format!("{name}: seed {i}"), seed, &check);
    }
    for len in 0..seeds[0].len().min(64) {
        assert_no_panic(&format!("{name}: prefix {len}"), &seeds[0][..len], &check);
    }
    let mut rng = Rng::for_test(name);
    for iter in 0..iterations(default_iters) {
        let pick = rng.below(seeds.len());
        let input = mutate(&mut rng, &seeds[pick]);
        assert_no_panic(
            &format!("{name}: iteration {iter} (seed {pick})"),
            &input,
            &check,
        );
    }
}

/// Little-endian byte-buffer writer for building fixtures.
#[derive(Debug, Default, Clone)]
pub struct Buf(pub Vec<u8>);

impl Buf {
    /// An empty buffer.
    #[must_use]
    pub fn new() -> Buf {
        Buf(Vec::new())
    }

    /// A zero-filled buffer of `len` bytes.
    #[must_use]
    pub fn zeroed(len: usize) -> Buf {
        Buf(vec![0; len])
    }

    /// Current length.
    #[must_use]
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// True when empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Append a byte.
    pub fn u8(&mut self, v: u8) -> &mut Buf {
        self.0.push(v);
        self
    }

    /// Append a little-endian u16.
    pub fn u16(&mut self, v: u16) -> &mut Buf {
        self.0.extend_from_slice(&v.to_le_bytes());
        self
    }

    /// Append a little-endian u32.
    pub fn u32(&mut self, v: u32) -> &mut Buf {
        self.0.extend_from_slice(&v.to_le_bytes());
        self
    }

    /// Append a little-endian f32.
    pub fn f32(&mut self, v: f32) -> &mut Buf {
        self.u32(v.to_bits())
    }

    /// Append raw bytes.
    pub fn bytes(&mut self, v: &[u8]) -> &mut Buf {
        self.0.extend_from_slice(v);
        self
    }

    /// Append zero bytes until the length is a multiple of `align`.
    pub fn align(&mut self, align: usize) -> &mut Buf {
        while !self.0.len().is_multiple_of(align) {
            self.0.push(0);
        }
        self
    }

    /// Overwrite a little-endian u32 at `at` (the buffer grows if needed).
    pub fn put_u32(&mut self, at: usize, v: u32) -> &mut Buf {
        self.put(at, &v.to_le_bytes())
    }

    /// Overwrite a little-endian u16 at `at` (the buffer grows if needed).
    pub fn put_u16(&mut self, at: usize, v: u16) -> &mut Buf {
        self.put(at, &v.to_le_bytes())
    }

    /// Overwrite a little-endian f32 at `at` (the buffer grows if needed).
    pub fn put_f32(&mut self, at: usize, v: f32) -> &mut Buf {
        self.put_u32(at, v.to_bits())
    }

    /// Overwrite bytes at `at` (the buffer grows if needed).
    pub fn put(&mut self, at: usize, v: &[u8]) -> &mut Buf {
        if self.0.len() < at + v.len() {
            self.0.resize(at + v.len(), 0);
        }
        self.0[at..at + v.len()].copy_from_slice(v);
        self
    }
}

/// Adler-32 checksum (the zlib trailer).
#[must_use]
pub fn adler32(data: &[u8]) -> u32 {
    let (mut a, mut b) = (1u32, 0u32);
    for &x in data {
        a = (a + u32::from(x)) % ADLER_MOD;
        b = (b + a) % ADLER_MOD;
    }
    (b << 16) | a
}

/// A zlib stream holding `data` in stored (uncompressed) deflate blocks,
/// starting with the header bytes `78 DA` that RSC5 files carry. Any zlib
/// reader inflates it; no compressor is needed.
#[must_use]
pub fn zlib_stored(data: &[u8]) -> Vec<u8> {
    let mut out = vec![0x78, 0xDA];
    let mut chunks = data.chunks(STORED_BLOCK_MAX).peekable();
    if chunks.peek().is_none() {
        out.extend_from_slice(&[0x01, 0x00, 0x00, 0xFF, 0xFF]);
    }
    while let Some(chunk) = chunks.next() {
        out.push(u8::from(chunks.peek().is_none()));
        let n = chunk.len() as u16;
        out.extend_from_slice(&n.to_le_bytes());
        out.extend_from_slice(&(!n).to_le_bytes());
        out.extend_from_slice(chunk);
    }
    out.extend_from_slice(&adler32(data).to_be_bytes());
    out
}

/// Encode one segment size for the RSC5 flags word: the smallest exponent
/// whose unit lets the mantissa fit. Returns `(mantissa, exponent, padded)`.
fn rsc5_size(len: usize) -> (u32, u32, usize) {
    for exponent in 0..16u32 {
        let unit = 256usize << exponent;
        let mantissa = len.div_ceil(unit);
        if mantissa <= RSC5_MANTISSA_MAX {
            return (mantissa as u32, exponent, mantissa * unit);
        }
    }
    panic!("segment of {len} bytes is too large for a fixture");
}

/// An RSC5 file of type `kind` holding `sys` and `gfx`. Each segment is
/// zero-padded to the size the flags word can express, and bit 31 of the
/// flags is set as on PC files.
#[must_use]
pub fn rsc5(kind: u32, sys: &[u8], gfx: &[u8]) -> Vec<u8> {
    let (sys_a, sys_b, sys_len) = rsc5_size(sys.len());
    let (gfx_a, gfx_b, gfx_len) = rsc5_size(gfx.len());
    let flags = sys_a | (sys_b << 11) | (gfx_a << 15) | (gfx_b << 26) | (1 << 31);
    let mut payload = Vec::with_capacity(sys_len + gfx_len);
    payload.extend_from_slice(sys);
    payload.resize(sys_len, 0);
    payload.extend_from_slice(gfx);
    payload.resize(sys_len + gfx_len, 0);
    let mut file = Vec::new();
    file.extend_from_slice(&RSC5_MAGIC.to_le_bytes());
    file.extend_from_slice(&kind.to_le_bytes());
    file.extend_from_slice(&flags.to_le_bytes());
    file.extend_from_slice(&zlib_stored(&payload));
    file
}

/// Split a fuzzed payload back into `(system, graphics)` at `sys_len`
/// (clamped), for fuzzers that mutate the inflated segments of an RSC5 file
/// and re-wrap them with [`rsc5`].
#[must_use]
pub fn split_at_clamped(bytes: &[u8], sys_len: usize) -> (&[u8], &[u8]) {
    bytes.split_at(sys_len.min(bytes.len()))
}
