//! Mainloop-timing callback registrations: one descriptor per verified member.
//!
//! GENERATED FILE - do not edit by hand (lane `gen2.py`). The descriptor
//! is a name plus an index token; the 32-bit addresses each member was
//! verified with live only in the differential test's case table, never here.

use crate::TimerDesc;

/// One descriptor per verified member, in case-table order.
pub const DESCS: &[TimerDesc] = &[
    TimerDesc { name: "00", index: 0 },
    TimerDesc { name: "650", index: 1 },
    TimerDesc { name: "660", index: 2 },
    TimerDesc { name: "670", index: 3 },
    TimerDesc { name: "680", index: 4 },
    TimerDesc { name: "e6e6b0", index: 5 },
    TimerDesc { name: "e6e6c0", index: 6 },
    TimerDesc { name: "e6e6d0", index: 7 },
    TimerDesc { name: "e6e6e0", index: 8 },
    TimerDesc { name: "e6e6f0", index: 9 },
    TimerDesc { name: "e6e700", index: 10 },
    TimerDesc { name: "e6e710", index: 11 },
    TimerDesc { name: "e6e720", index: 12 },
    TimerDesc { name: "e6e730", index: 13 },
    TimerDesc { name: "e6e740", index: 14 },
    TimerDesc { name: "e6e750", index: 15 },
    TimerDesc { name: "e6e760", index: 16 },
    TimerDesc { name: "e6e770", index: 17 },
    TimerDesc { name: "register_callback_00e5efe0", index: 18 },
    TimerDesc { name: "register_callback_00e5eff0", index: 19 },
    TimerDesc { name: "register_callback_00e5f000", index: 20 },
    TimerDesc { name: "register_callback_00e5f010", index: 21 },
    TimerDesc { name: "callback_forwarder_e6f600", index: 22 },
    TimerDesc { name: "callback_forwarder_e6f610", index: 23 },
    TimerDesc { name: "callback_forwarder_e6f640", index: 24 },
    TimerDesc { name: "callback_forwarder_e6f650", index: 25 },
    TimerDesc { name: "callback_forwarder_e6f660", index: 26 },
    TimerDesc { name: "callback_forwarder_e6f680", index: 27 },
    TimerDesc { name: "callback_forwarder_e6f6b0", index: 28 },
    TimerDesc { name: "callback_forwarder_e6f900", index: 29 },
    TimerDesc { name: "callback_forwarder_e6f910", index: 30 },
    TimerDesc { name: "callback_forwarder_e6f950", index: 31 },
    TimerDesc { name: "timing_register_callback_01", index: 32 },
    TimerDesc { name: "timing_register_callback_02", index: 33 },
    TimerDesc { name: "forward_ptr_e6fda0", index: 34 },
    TimerDesc { name: "forward_ptr_e6fe00", index: 35 },
    TimerDesc { name: "forward_ptr_e6fe60", index: 36 },
    TimerDesc { name: "forward_ptr_e6fe80", index: 37 },
    TimerDesc { name: "forward_ptr_e6ff00", index: 38 },
    TimerDesc { name: "forward_ptr_e6ff30", index: 39 },
    TimerDesc { name: "forward_ptr_e6ff60", index: 40 },
    TimerDesc { name: "forward_ptr_e6ff70", index: 41 },
    TimerDesc { name: "forward_ptr_e6ff80", index: 42 },
    TimerDesc { name: "forward_ptr_e6ff90", index: 43 },
    TimerDesc { name: "forward_ptr_e6fff0", index: 44 },
    TimerDesc { name: "timing_register_callback_a", index: 45 },
    TimerDesc { name: "timing_register_callback_b", index: 46 },
    TimerDesc { name: "timing_register_callback_c", index: 47 },
    TimerDesc { name: "timing_callback_register_1", index: 48 },
    TimerDesc { name: "timing_callback_register_2", index: 49 },
    TimerDesc { name: "timing_callback_register_3", index: 50 },
    TimerDesc { name: "timing_callback_register_4", index: 51 },
    TimerDesc { name: "timing_callback_register_5", index: 52 },
    TimerDesc { name: "net_regfwd_01", index: 53 },
    TimerDesc { name: "net_regfwd_02", index: 54 },
    TimerDesc { name: "net_regfwd_03", index: 55 },
    TimerDesc { name: "net_regfwd_04", index: 56 },
    TimerDesc { name: "net_regfwd_05", index: 57 },
    TimerDesc { name: "net_regfwd_06", index: 58 },
    TimerDesc { name: "net_regfwd_07", index: 59 },
    TimerDesc { name: "net_regfwd_08", index: 60 },
    TimerDesc { name: "net_regfwd_09", index: 61 },
    TimerDesc { name: "net_regfwd_10", index: 62 },
    TimerDesc { name: "net_regfwd_11", index: 63 },
    TimerDesc { name: "net_regfwd_12", index: 64 },
    TimerDesc { name: "net_regfwd_13", index: 65 },
    TimerDesc { name: "net_regfwd_14", index: 66 },
    TimerDesc { name: "net_regfwd_15", index: 67 },
    TimerDesc { name: "net_regfwd_16", index: 68 },
    TimerDesc { name: "net_regfwd_17", index: 69 },
    TimerDesc { name: "test_code_hook_e712e0", index: 70 },
    TimerDesc { name: "test_code_hook_e71300", index: 71 },
    TimerDesc { name: "init_callback_e713d0", index: 72 },
    TimerDesc { name: "init_callback_e713e0", index: 73 },
    TimerDesc { name: "notify_code_ptr_1", index: 74 },
    TimerDesc { name: "notify_code_ptr_2", index: 75 },
    TimerDesc { name: "notify_code_ptr_3", index: 76 },
    TimerDesc { name: "notify_block_a", index: 77 },
    TimerDesc { name: "notify_block_b", index: 78 },
    TimerDesc { name: "notify_block_c", index: 79 },
    TimerDesc { name: "audio_callback_register", index: 80 },
];
