//! Per-asset slot registrations: one descriptor per verified member.
//!
//! GENERATED FILE - do not edit by hand (lane `gen2.py`). The descriptor
//! is a name plus an index token; the 32-bit addresses each member was
//! verified with live only in the differential test's case table, never here.

use crate::AssetDesc;

/// One descriptor per verified member, in case-table order.
pub const DESCS: &[AssetDesc] = &[
    AssetDesc { name: "bullet", index: 0 },
    AssetDesc { name: "burrito_00e67850", index: 1 },
    AssetDesc { name: "bus", index: 2 },
    AssetDesc { name: "cabby", index: 3 },
    AssetDesc { name: "cablecar", index: 4 },
    AssetDesc { name: "taxi", index: 5 },
    AssetDesc { name: "taxi2", index: 6 },
    AssetDesc { name: "cognoscenti", index: 7 },
    AssetDesc { name: "comet", index: 8 },
    AssetDesc { name: "emperor2", index: 9 },
    AssetDesc { name: "emperor", index: 10 },
    AssetDesc { name: "fbi", index: 11 },
    AssetDesc { name: "firetruk", index: 12 },
    AssetDesc { name: "flatbed", index: 13 },
    AssetDesc { name: "trash", index: 14 },
    AssetDesc { name: "gburrito", index: 15 },
    AssetDesc { name: "hakumai", index: 16 },
    AssetDesc { name: "mrtasty", index: 17 },
    AssetDesc { name: "stretch", index: 18 },
    AssetDesc { name: "mule", index: 19 },
    AssetDesc { name: "n_mule", index: 20 },
    AssetDesc { name: "noose", index: 21 },
    AssetDesc { name: "nstockade", index: 22 },
    AssetDesc { name: "packer", index: 23 },
    AssetDesc { name: "phantom", index: 24 },
    AssetDesc { name: "police_00e679d0", index: 25 },
    AssetDesc { name: "pbus", index: 26 },
    AssetDesc { name: "police2", index: 27 },
    AssetDesc { name: "n_police2", index: 28 },
    AssetDesc { name: "police3", index: 29 },
    AssetDesc { name: "police4", index: 30 },
    AssetDesc { name: "police_00e67a30", index: 31 },
    AssetDesc { name: "n_police", index: 32 },
    AssetDesc { name: "polpatriot", index: 33 },
    AssetDesc { name: "n_polpatriot", index: 34 },
    AssetDesc { name: "pony", index: 35 },
    AssetDesc { name: "pstockade", index: 36 },
    AssetDesc { name: "n_pstockade", index: 37 },
    AssetDesc { name: "robin", index: 38 },
    AssetDesc { name: "sabre2", index: 39 },
    AssetDesc { name: "sabre", index: 40 },
    AssetDesc { name: "stockade", index: 41 },
    AssetDesc { name: "slamvan", index: 42 },
    AssetDesc { name: "speedo", index: 43 },
    AssetDesc { name: "steed", index: 44 },
    AssetDesc { name: "subway_lo", index: 45 },
    AssetDesc { name: "supergt", index: 46 },
    AssetDesc { name: "empty_00e67b30", index: 47 },
    AssetDesc { name: "empty_00e67b40", index: 48 },
    AssetDesc { name: "turismo", index: 49 },
    AssetDesc { name: "vigero2", index: 50 },
    AssetDesc { name: "vigero", index: 51 },
    AssetDesc { name: "yankee", index: 52 },
    AssetDesc { name: "M_Y_CELEBBLOG", index: 53 },
    AssetDesc { name: "CJ_MOBILE_HAND_1", index: 54 },
    AssetDesc { name: "CJ_EXT_DOOR_16", index: 55 },
    AssetDesc { name: "CJ_EXT_DOOR_17", index: 56 },
    AssetDesc { name: "CJ_EXT_DOOR_1", index: 57 },
    AssetDesc { name: "CJ_LD_MET_DOOR_L", index: 58 },
    AssetDesc { name: "CJ_SHOP_DOOR_1", index: 59 },
    AssetDesc { name: "p_e2_crane_1", index: 60 },
    AssetDesc { name: "boxville", index: 61 },
    AssetDesc { name: "burrito_00e67c20", index: 62 },
    AssetDesc { name: "E2_MAISONDOOR18", index: 63 },
    AssetDesc { name: "E2_CJ_BIG_BOAT_1", index: 64 },
    AssetDesc { name: "e2_cj_boat_lod", index: 65 },
    AssetDesc { name: "E2_BOAT_MAIN_LOD", index: 66 },
    AssetDesc { name: "E2_BOAT_BOW_LOD", index: 67 },
    AssetDesc { name: "BOAT_BOW_DAM_LOD", index: 68 },
    AssetDesc { name: "E2_BOAT_TOP_LOD", index: 69 },
    AssetDesc { name: "BOAT_TOP_DAM_LOD", index: 70 },
    AssetDesc { name: "E2_BOAT_TOP2_LOD", index: 71 },
    AssetDesc { name: "BOAT_TOP2_DAM_LOD", index: 72 },
    AssetDesc { name: "E2_BOAT_TOP3_LOD", index: 73 },
    AssetDesc { name: "BOAT_TOP3_DAM_LOD", index: 74 },
    AssetDesc { name: "E2_BOAT_STERN_LOD", index: 75 },
    AssetDesc { name: "BOAT_STERN_DAM_LOD", index: 76 },
    AssetDesc { name: "nj5btmp", index: 77 },
    AssetDesc { name: "lod_nj5btmp", index: 78 },
    AssetDesc { name: "lod_nj5btmp02", index: 79 },
];
