//! Lifted `rlConcreteLeaderboardInfo` template family (lane l-lb1 draft).
//!
//! The original instantiates one leaderboard-info class per leaderboard
//! (several hundred), each with the same eight virtual slots. The verified
//! rewrites prove each instantiation separately in the checker's 32-bit
//! form; this crate restates each slot once, as portable Rust following the
//! lift method (`documentation/lift-method.md`, `lf-lift` crate docs):
//!
//! - No addresses: tables are slices, objects are structs, the per-board
//!   tag is an opaque [`Tag`]. The 32-bit fetch block layout lives only in
//!   the differential tests, never here.
//! - No numbered callee slots: collaborators are [`tables::BoardTables`]
//!   trait methods, statically dispatched.
//! - No global state: every function takes what it touches.
//! - No dependence on pointer width: the original's `u32` words stay `u32`;
//!   `usize` is only an element index. Arithmetic wraps exactly where the
//!   original's wraps.
//! - `#![forbid(unsafe_code)]`.
//!
//! What varies per instantiation is one [`desc::LeaderboardDesc`]; the table
//! for every verified instantiation is generated by script from the
//! verified rewrites (see `desc.rs`). Proof is differential: each slot
//! function against every verified rewrite of that slot on the same
//! generated inputs (crate `lf-lb-diff`, 32-bit target).
//!
//! Status: the six table slots are lifted and proven. The probe slot, the
//! row collector and the constructors are designed (descriptors generated)
//! but not yet proven; see [`registry`] and the lane report.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod desc;
pub mod registry;
pub mod tables;

pub use desc::LeaderboardDesc;
pub use tables::BoardTables;
pub use tables::BoardView;

/// Opaque identity of one board's tag word (the probe slot's answer).
///
/// Stand-in for `lf_core::Handle32` until this crate joins the workspace:
/// a 32-bit cookie the lifted code carries but never interprets.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Tag(u32);

impl Tag {
    /// Wraps a raw cookie.
    #[must_use]
    pub const fn new(raw: u32) -> Self {
        Self(raw)
    }

    /// The raw cookie, for the boundary only.
    #[must_use]
    pub const fn get(self) -> u32 {
        self.0
    }
}
