//! The replacement table a rewrite library exports, and its conversion
//! into [`HookDef`]s.
//!
//! The assembled rewrite library (`lf-rewrite-32`, generated by
//! `scripts/assemble/assemble.py`) exports
//! `lf_rewrite_table(out_len: *mut u32) -> *const RewriteEntry`: one
//! [`RewriteEntry`] per included rewrite, in address order. The layout is a
//! fixed C ABI so the loader can read it across the DLL boundary; every
//! field is an integer, so the type is plain data on every target.
//!
//! Conversion rules ([`plan`]):
//! - Only entries with [`FLAG_SWITCHABLE`] become hooks. The generator
//!   clears the flag when a rewrite cannot run in the game yet (a callee
//!   slot without a known original address, a checker-only input such as
//!   the scripted XMM mirror). Those entries are reported, never hooked.
//! - The hook target is an inline 5-byte hook at the original address,
//!   rebased from [`PREFERRED_BASE`]. The detour is the rewrite's own entry
//!   point: rewrites are compiled in the original's calling convention
//!   (`cdecl`, `stdcall`, `thiscall`, `fastcall` are all stable Rust ABIs on
//!   x86), so no adapter stub sits between the patch and the rewrite.
//! - Names are the control-file handles (`function.00501230`); a name with
//!   whitespace or `#` could not be addressed from `switches.lf` and is
//!   refused, as are duplicate names and duplicate addresses.
//! - Every hook starts off; the per-function switch is the registry state,
//!   driven by `switches.lf` exactly like hand-written hooks.

// Reading the name and expected-byte arrays of an exported table follows
// raw pointers into the rewrite library's read-only data; only
// `read_rows` does that, and its contract is stated on it.
#![allow(unsafe_code)]

use crate::{HookDef, Target};
use std::collections::HashSet;

/// Version of the table layout below; `lf_rewrite_version` returns it.
/// 0 means the library exports no table.
pub const TABLE_ABI_VERSION: u32 = 1;

/// Image base the original addresses in the table are relative to.
pub const PREFERRED_BASE: u32 = 0x0040_0000;

/// `conv` value: `cdecl` (caller cleans the stack).
pub const CONV_CDECL: u8 = 0;
/// `conv` value: `stdcall` (callee cleans the stack).
pub const CONV_STDCALL: u8 = 1;
/// `conv` value: `thiscall` (`this` in ECX, callee cleans the stack).
pub const CONV_THISCALL: u8 = 2;
/// `conv` value: `fastcall` (first two arguments in ECX and EDX).
pub const CONV_FASTCALL: u8 = 3;

/// `flags` bit: the rewrite may be switched on in the game.
pub const FLAG_SWITCHABLE: u8 = 1 << 0;
/// `flags` bit: the rewrite calls callees through the stub table.
pub const FLAG_USES_CALLEES: u8 = 1 << 1;
/// `flags` bit: every callee slot it uses maps to an original address.
pub const FLAG_CALLEES_MAPPED: u8 = 1 << 2;
/// `flags` bit: it reads a checker-only input (scripted XMM or TLS mirror).
pub const FLAG_CHECKER_ONLY: u8 = 1 << 3;

/// One exported table row (C layout; 28 bytes on x86).
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct RewriteEntry {
    /// Original function address at [`PREFERRED_BASE`].
    pub address: u32,
    /// One of the `CONV_*` values: the convention both sides share.
    pub conv: u8,
    /// `FLAG_*` bits.
    pub flags: u8,
    /// Index of the shard crate the rewrite was compiled in.
    pub shard: u16,
    /// Address of the rewrite's entry point.
    pub detour: usize,
    /// Address of the ASCII control handle (not NUL-terminated).
    pub name_ptr: usize,
    /// Address of the bytes expected at the original before patching
    /// (0 when the table carries none).
    pub expected_ptr: usize,
    /// Length of the control handle in bytes.
    pub name_len: u32,
    /// Number of expected bytes (0 skips the check).
    pub expected_len: u32,
}

impl RewriteEntry {
    /// True when [`FLAG_SWITCHABLE`] is set.
    #[must_use]
    pub fn is_switchable(&self) -> bool {
        self.flags & FLAG_SWITCHABLE != 0
    }
}

/// Name of a `CONV_*` value, or `None` for an unknown one.
#[must_use]
pub fn conv_name(conv: u8) -> Option<&'static str> {
    match conv {
        CONV_CDECL => Some("cdecl"),
        CONV_STDCALL => Some("stdcall"),
        CONV_THISCALL => Some("thiscall"),
        CONV_FASTCALL => Some("fastcall"),
        _ => None,
    }
}

/// One table row with its name and expected bytes read out.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Row {
    /// The raw entry.
    pub entry: RewriteEntry,
    /// Control handle.
    pub name: String,
    /// Bytes expected at the original before patching (may be empty).
    pub expected: Vec<u8>,
}

/// Read every row of an exported table.
///
/// # Safety
///
/// `table` must point at `len` valid [`RewriteEntry`] values, and every
/// entry's `name_ptr`/`name_len` and `expected_ptr`/`expected_len` must
/// describe readable bytes, all for as long as this call runs. A table
/// returned by a loaded rewrite library's `lf_rewrite_table` meets this:
/// it and everything it points at are static data of that library.
#[must_use]
pub unsafe fn read_rows(table: *const RewriteEntry, len: usize) -> Vec<Row> {
    if table.is_null() || len == 0 {
        return Vec::new();
    }
    // SAFETY: the caller guarantees `len` readable entries at `table`.
    let entries = unsafe { std::slice::from_raw_parts(table, len) };
    entries
        .iter()
        .map(|entry| {
            // SAFETY: the caller guarantees the name and expected ranges.
            let name = unsafe { bytes_at(entry.name_ptr, entry.name_len) };
            let expected = unsafe { bytes_at(entry.expected_ptr, entry.expected_len) };
            Row {
                entry: *entry,
                name: String::from_utf8_lossy(&name).into_owned(),
                expected,
            }
        })
        .collect()
}

/// Copy `len` bytes at `addr` (empty for a null address or zero length).
///
/// # Safety
///
/// A non-null `addr` must have `len` readable bytes.
unsafe fn bytes_at(addr: usize, len: u32) -> Vec<u8> {
    if addr == 0 || len == 0 {
        return Vec::new();
    }
    // SAFETY: the caller guarantees `len` readable bytes at `addr`.
    unsafe { std::slice::from_raw_parts(addr as *const u8, len as usize) }.to_vec()
}

/// Why a table row did not become a hook.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Skip {
    /// [`FLAG_SWITCHABLE`] is clear (the generator's manifest says why).
    NotSwitchable,
    /// The detour address is 0.
    NullDetour,
    /// The address lies below [`PREFERRED_BASE`].
    BelowBase,
    /// The `conv` value is not one of the `CONV_*` values.
    UnknownConvention(u8),
    /// The name is empty or holds whitespace or `#`.
    BadName,
    /// An earlier row already uses this name.
    DuplicateName,
    /// An earlier row already hooks this address.
    DuplicateAddress,
}

/// The outcome of [`plan`]: hooks to register and rows left out.
#[derive(Clone, Debug, Default)]
pub struct TablePlan {
    /// Hooks to register, table order.
    pub defs: Vec<HookDef>,
    /// `(name, address, reason)` for every row left out.
    pub skipped: Vec<(String, u32, Skip)>,
}

/// Subsystem name used for bulk toggles of one shard (`sub:s007 on`).
#[must_use]
pub fn shard_subsystem(shard: u16) -> String {
    format!("s{shard:03}")
}

/// Turn table rows into hook definitions (see the module rules).
#[must_use]
pub fn plan(rows: &[Row]) -> TablePlan {
    let mut out = TablePlan::default();
    let mut names = HashSet::new();
    let mut addresses = HashSet::new();
    for row in rows {
        let e = &row.entry;
        let reason = if !e.is_switchable() {
            Some(Skip::NotSwitchable)
        } else if e.detour == 0 {
            Some(Skip::NullDetour)
        } else if e.address < PREFERRED_BASE {
            Some(Skip::BelowBase)
        } else if conv_name(e.conv).is_none() {
            Some(Skip::UnknownConvention(e.conv))
        } else if row.name.is_empty()
            || row.name.chars().any(|c| c.is_whitespace() || c == '#')
        {
            Some(Skip::BadName)
        } else if names.contains(&row.name) {
            Some(Skip::DuplicateName)
        } else if addresses.contains(&e.address) {
            Some(Skip::DuplicateAddress)
        } else {
            None
        };
        if let Some(reason) = reason {
            out.skipped.push((row.name.clone(), e.address, reason));
            continue;
        }
        names.insert(row.name.clone());
        addresses.insert(e.address);
        out.defs.push(HookDef {
            name: row.name.clone(),
            subsystem: shard_subsystem(e.shard),
            target: Target::Inline {
                rva: e.address - PREFERRED_BASE,
                expected: row.expected.clone(),
                follow_jumps: false,
            },
            detour: e.detour,
        });
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(address: u32, name: &str, flags: u8) -> Row {
        Row {
            entry: RewriteEntry {
                address,
                conv: CONV_THISCALL,
                flags,
                shard: 2,
                detour: 0x1000_0000 + address as usize,
                ..RewriteEntry::default()
            },
            name: name.to_string(),
            expected: vec![0x55, 0x8B, 0xEC],
        }
    }

    #[test]
    fn layout_is_fixed() {
        let ptr = std::mem::size_of::<usize>();
        assert_eq!(std::mem::size_of::<RewriteEntry>(), 8 + 3 * ptr + 8);
        assert_eq!(std::mem::offset_of!(RewriteEntry, conv), 4);
        assert_eq!(std::mem::offset_of!(RewriteEntry, shard), 6);
        assert_eq!(std::mem::offset_of!(RewriteEntry, detour), 8);
        if ptr == 4 {
            assert_eq!(std::mem::size_of::<RewriteEntry>(), 28);
            assert_eq!(std::mem::offset_of!(RewriteEntry, name_len), 20);
        }
    }

    #[test]
    fn switchable_rows_become_inline_hooks() {
        let p = plan(&[row(0x0050_1230, "function.00501230", FLAG_SWITCHABLE)]);
        assert!(p.skipped.is_empty());
        assert_eq!(p.defs.len(), 1);
        let d = &p.defs[0];
        assert_eq!(d.name, "function.00501230");
        assert_eq!(d.subsystem, "s002");
        assert_eq!(d.detour, 0x1050_1230);
        match &d.target {
            Target::Inline {
                rva,
                expected,
                follow_jumps,
            } => {
                assert_eq!(*rva, 0x0010_1230);
                assert_eq!(expected, &vec![0x55, 0x8B, 0xEC]);
                assert!(!follow_jumps);
            }
            other => panic!("unexpected target {other:?}"),
        }
    }

    #[test]
    fn rows_left_out_say_why() {
        let mut null = row(0x0050_0040, "function.00500040", FLAG_SWITCHABLE);
        null.entry.detour = 0;
        let mut conv = row(0x0050_0050, "function.00500050", FLAG_SWITCHABLE);
        conv.entry.conv = 9;
        let rows = vec![
            row(0x0050_0000, "function.00500000", FLAG_USES_CALLEES),
            row(0x0050_0010, "function.00500010", FLAG_SWITCHABLE),
            row(0x0050_0020, "function.00500010", FLAG_SWITCHABLE),
            row(0x0050_0010, "function.other", FLAG_SWITCHABLE),
            row(0x0010_0000, "function.00100000", FLAG_SWITCHABLE),
            row(0x0050_0030, "has space", FLAG_SWITCHABLE),
            row(0x0050_0031, "", FLAG_SWITCHABLE),
            null,
            conv,
        ];
        let p = plan(&rows);
        assert_eq!(p.defs.len(), 1);
        let reasons: Vec<Skip> = p.skipped.iter().map(|s| s.2.clone()).collect();
        assert_eq!(
            reasons,
            vec![
                Skip::NotSwitchable,
                Skip::DuplicateName,
                Skip::DuplicateAddress,
                Skip::BelowBase,
                Skip::BadName,
                Skip::BadName,
                Skip::NullDetour,
                Skip::UnknownConvention(9),
            ]
        );
    }

    #[test]
    fn plan_feeds_the_control_file() {
        // Hooks from a table answer to the same control lines as any other.
        let p = plan(&[
            row(0x0050_0000, "function.00500000", FLAG_SWITCHABLE),
            row(0x0050_0010, "native.00500010", FLAG_SWITCHABLE),
        ]);
        let names: Vec<&str> = p.defs.iter().map(|d| d.name.as_str()).collect();
        let cmds = crate::parse_control(&format!("{} on\nsub:s002 off\n", names[1]));
        assert_eq!(
            cmds[0],
            Ok(crate::Command::One {
                name: "native.00500010".to_string(),
                on: true
            })
        );
        assert_eq!(
            cmds[1],
            Ok(crate::Command::Subsystem {
                name: p.defs[0].subsystem.clone(),
                on: false
            })
        );
    }

    #[test]
    fn rows_read_from_a_raw_table() {
        static NAME: &[u8] = b"function.00501230";
        static EXPECTED: &[u8] = &[0x6A, 0xFF];
        let entries = [
            RewriteEntry {
                address: 0x0050_1230,
                flags: FLAG_SWITCHABLE,
                detour: 0x1234,
                name_ptr: NAME.as_ptr() as usize,
                name_len: NAME.len() as u32,
                expected_ptr: EXPECTED.as_ptr() as usize,
                expected_len: 2,
                ..RewriteEntry::default()
            },
            RewriteEntry::default(),
        ];
        // SAFETY: both entries point at static data or at nothing.
        let rows = unsafe { read_rows(entries.as_ptr(), entries.len()) };
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].name, "function.00501230");
        assert_eq!(rows[0].expected, vec![0x6A, 0xFF]);
        assert_eq!(rows[1].name, "");
        assert!(rows[1].expected.is_empty());
        // SAFETY: a null table is accepted and yields nothing.
        assert!(unsafe { read_rows(std::ptr::null(), 4) }.is_empty());
    }

    #[test]
    fn convention_names() {
        assert_eq!(conv_name(CONV_CDECL), Some("cdecl"));
        assert_eq!(conv_name(CONV_STDCALL), Some("stdcall"));
        assert_eq!(conv_name(CONV_THISCALL), Some("thiscall"));
        assert_eq!(conv_name(CONV_FASTCALL), Some("fastcall"));
        assert_eq!(conv_name(4), None);
    }
}
