param(
    [Parameter(Mandatory = $true)][string]$Lane,
    [string]$Effort = "max"
)
# Runs one Muse Spark lane against its brief. Do not edit this file while lanes are running.
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent (Split-Path -Parent $here)
$coord = "$root\.artifacts\scratch\coordinator"
$brief = "$coord\briefs\$Lane.txt"
$log = "$root\.artifacts\logs\$Lane.log"
New-Item -ItemType Directory -Force -Path "$root\.artifacts\scratch\$Lane", "$root\.artifacts\logs" | Out-Null
Set-Location $root
Add-Content -Path $log -Value ("{0} coordinator: lane launched" -f (Get-Date -Format "HH:mm:ss"))
& muse exec --model muse-spark-1.3-contributor --reasoning-effort $Effort --approval-mode never `
    --disable-sandbox --trust-workspace --no-session-log --workspace $root --prompt-file $brief
$code = $LASTEXITCODE
Add-Content -Path $log -Value ("{0} coordinator: lane exited with code {1}" -f (Get-Date -Format "HH:mm:ss"), $code)
"LANE $Lane EXIT=$code"
