//! Lifted script-native dispatch (lane l-lb2 draft).
//!
//! Every script native handler in the original is one routine instantiated
//! per native: read the script words from the call context, boolean-coerce
//! the flagged ones, call the engine worker, and either discard its answer
//! or store it (masked to a byte or whole) into the return slot. The
//! verified rewrites prove each instantiation separately in the checker's
//! 32-bit form; this crate restates the routine three times (once per
//! return convention) as portable Rust following the lift method:
//!
//! - No addresses: the context layout (slot pointer first, argument array
//!   second) stays at the boundary. The lift takes a word slice and, where
//!   the shape stores, a mutable slot.
//! - No numbered callee slots: the engine worker is [`NativeEngine::call`].
//! - No global state: every function takes what it touches.
//! - No dependence on pointer width: words stay `u32`; `usize` is only an
//!   index. The `!= 0` coercions and the byte mask wrap/compare exactly as
//!   the original's do.
//! - `#![forbid(unsafe_code)]`.
//!
//! What varies per instantiation is one [`NativeDesc`]: the native's name
//! and hash (the dispatch entry), how many script words it forwards, and
//! which words are boolean-coerced. The table for every verified handler is
//! generated by script from the verified rewrites (see `desc.rs`). Proof is
//! differential: each function against every verified rewrite of its shape
//! on the same generated inputs (crate `lf-fam-diff`, 32-bit target).
//!
//! Future home: a module of `lf-script` (script threads and the script VM).

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod desc;

/// One native's dispatch entry: identity plus call shape.
///
/// The 32-bit form's stack-slot quirk (a coerced flag pushed with the
/// context address in its high bytes) is NOT reproduced here: the engine
/// reads only the low byte, so the lift passes the clean flag and the
/// differential test pins the residue formula per member.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct NativeDesc {
    /// Native name from the verified symbol, for debugging.
    pub name: &'static str,
    /// Native hash from the rewrite's doc comment (0 when unstated).
    pub hash: u32,
    /// Script words forwarded to the engine.
    pub nargs: u8,
    /// Bit `k` set: word `k` is boolean-coerced (`word != 0`).
    pub coerce: u32,
    /// Coerced word whose 32-bit form keeps context high bytes, else -1.
    /// Test-side only: the lift never reads this field.
    pub quirk: i8,
    /// Reserved: context-forwarding tail jumps are deferred, never generated.
    pub forwards_ctx: bool,
}

/// The engine side of native dispatch: runs one native by its entry.
pub trait NativeEngine {
    /// Runs `native` with the (already coerced) script words.
    fn call(&mut self, native: &NativeDesc, args: &[u32]) -> u32;
}

/// Largest verified argument count, plus room (observed maximum is 17).
const MAX_ARGS: usize = 24;

/// The words one handler forwards: the first `desc.nargs` words of `args`
/// with the descriptor's coercions applied.
///
/// # Panics
///
/// When `args` holds fewer than `desc.nargs` words (a caller bug: the
/// original reads exactly `nargs` words) or `desc.nargs` exceeds [`MAX_ARGS`]
/// (a descriptor bug). Every differential case feeds at least `nargs` words.
fn forward_words(desc: &NativeDesc, args: &[u32], out: &mut [u32; MAX_ARGS]) -> usize {
    let n = desc.nargs as usize;
    assert!(
        n <= MAX_ARGS,
        "{}: descriptor wants {n} words, more than {MAX_ARGS}",
        desc.name
    );
    let argv = args.get(..n).unwrap_or_else(|| {
        panic!(
            "{}: got {} script words, descriptor wants {n}",
            desc.name,
            args.len()
        )
    });
    for (i, &w) in argv.iter().enumerate() {
        out[i] = if desc.coerce >> i & 1 == 1 {
            u32::from(w != 0)
        } else {
            w
        };
    }
    n
}

/// A no-return native: forward the words, return the engine's answer.
///
/// The 32-bit form returns the worker's answer word unchanged and writes no
/// return slot; so does this function (it takes no slot at all).
pub fn forward(eng: &mut impl NativeEngine, desc: &NativeDesc, args: &[u32]) -> u32 {
    let mut buf = [0u32; MAX_ARGS];
    let n = forward_words(desc, args, &mut buf);
    eng.call(desc, &buf[..n])
}

/// A boolean native: forward the words, store the answer's low byte.
///
/// The 32-bit form stores `answer & 0xFF` into the return slot and returns
/// either the slot address or the stored value (both spellings verified);
/// this function stores into `ret` and returns the stored value. The
/// differential test pins the slot-address shape per member.
pub fn forward_masked(
    eng: &mut impl NativeEngine,
    desc: &NativeDesc,
    args: &[u32],
    ret: &mut u32,
) -> u32 {
    let answer = forward(eng, desc, args);
    *ret = answer & 0xFF;
    *ret
}

/// An integer native: forward the words, store the whole answer.
///
/// The 32-bit form stores the full answer word (one spelling converts
/// through float bits, which preserves the bits) and returns either the
/// slot address or the stored value; this function stores into `ret` and
/// returns the stored value.
pub fn forward_full(
    eng: &mut impl NativeEngine,
    desc: &NativeDesc,
    args: &[u32],
    ret: &mut u32,
) -> u32 {
    let answer = forward(eng, desc, args);
    *ret = answer;
    *ret
}
