//! Vectors: [`Vec2`], [`Vec3`], [`Vec4`].
//!
//! All three share one set of component-wise operations, generated by
//! `impl_vector!`. Arithmetic operators are component-wise (`a * b` is the
//! Hadamard product); use `dot` and `cross` for the products with names.

use core::ops::{
    Add, AddAssign, Div, DivAssign, Index, IndexMut, Mul, MulAssign, Neg, Sub, SubAssign,
};

/// A two-component vector (texture coordinates, screen positions).
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec2 {
    /// First component.
    pub x: f32,
    /// Second component.
    pub y: f32,
}

/// A three-component vector (positions, directions, colours).
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec3 {
    /// First component.
    pub x: f32,
    /// Second component.
    pub y: f32,
    /// Third component.
    pub z: f32,
}

/// A four-component vector (homogeneous points, matrix columns, RGBA).
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec4 {
    /// First component.
    pub x: f32,
    /// Second component.
    pub y: f32,
    /// Third component.
    pub z: f32,
    /// Fourth component.
    pub w: f32,
}

/// Generates the operations every vector type shares.
macro_rules! impl_vector {
    ($t:ident, $n:literal, $($f:ident),+) => {
        impl $t {
            /// All components zero.
            pub const ZERO: $t = $t { $($f: 0.0),+ };
            /// All components one.
            pub const ONE: $t = $t { $($f: 1.0),+ };

            /// A vector with every component set to `v`.
            #[must_use]
            pub const fn splat(v: f32) -> $t {
                $t { $($f: v),+ }
            }

            /// The components as an array, in field order.
            #[must_use]
            pub const fn to_array(self) -> [f32; $n] {
                [$(self.$f),+]
            }

            /// Builds a vector from an array, in field order.
            #[must_use]
            pub const fn from_array(a: [f32; $n]) -> $t {
                let [$($f),+] = a;
                $t { $($f),+ }
            }

            /// The dot product.
            #[must_use]
            pub fn dot(self, rhs: $t) -> f32 {
                0.0 $(+ self.$f * rhs.$f)+
            }

            /// The squared length (cheaper than [`Self::length`]).
            #[must_use]
            pub fn length_squared(self) -> f32 {
                self.dot(self)
            }

            /// The Euclidean length.
            #[must_use]
            pub fn length(self) -> f32 {
                self.length_squared().sqrt()
            }

            /// Distance to `rhs`.
            #[must_use]
            pub fn distance(self, rhs: $t) -> f32 {
                (self - rhs).length()
            }

            /// The unit vector in the same direction. A zero or non-finite
            /// vector gives non-finite components; use
            /// [`Self::try_normalize`] or [`Self::normalize_or_zero`] when
            /// that can happen.
            #[must_use]
            pub fn normalize(self) -> $t {
                self * (1.0 / self.length())
            }

            /// The unit vector, or `None` when the length is zero or the
            /// result would not be finite.
            #[must_use]
            pub fn try_normalize(self) -> Option<$t> {
                let len = self.length();
                if len > 0.0 && len.is_finite() {
                    Some(self * (1.0 / len))
                } else {
                    None
                }
            }

            /// The unit vector, or zero when it cannot be computed.
            #[must_use]
            pub fn normalize_or_zero(self) -> $t {
                self.try_normalize().unwrap_or($t::ZERO)
            }

            /// True when the length is within `eps` of 1.
            #[must_use]
            pub fn is_normalized(self, eps: f32) -> bool {
                (self.length_squared() - 1.0).abs() <= 2.0 * eps
            }

            /// Linear interpolation: `self` at `t = 0`, `rhs` at `t = 1`.
            #[must_use]
            pub fn lerp(self, rhs: $t, t: f32) -> $t {
                self + (rhs - self) * t
            }

            /// Component-wise minimum.
            #[must_use]
            pub fn min(self, rhs: $t) -> $t {
                $t { $($f: self.$f.min(rhs.$f)),+ }
            }

            /// Component-wise maximum.
            #[must_use]
            pub fn max(self, rhs: $t) -> $t {
                $t { $($f: self.$f.max(rhs.$f)),+ }
            }

            /// Component-wise absolute value.
            #[must_use]
            pub fn abs(self) -> $t {
                $t { $($f: self.$f.abs()),+ }
            }

            /// True when every component is finite.
            #[must_use]
            pub fn is_finite(self) -> bool {
                true $(&& self.$f.is_finite())+
            }
        }

        impl Add for $t {
            type Output = $t;
            fn add(self, rhs: $t) -> $t {
                $t { $($f: self.$f + rhs.$f),+ }
            }
        }

        impl Sub for $t {
            type Output = $t;
            fn sub(self, rhs: $t) -> $t {
                $t { $($f: self.$f - rhs.$f),+ }
            }
        }

        impl Mul for $t {
            type Output = $t;
            fn mul(self, rhs: $t) -> $t {
                $t { $($f: self.$f * rhs.$f),+ }
            }
        }

        impl Div for $t {
            type Output = $t;
            fn div(self, rhs: $t) -> $t {
                $t { $($f: self.$f / rhs.$f),+ }
            }
        }

        impl Mul<f32> for $t {
            type Output = $t;
            fn mul(self, rhs: f32) -> $t {
                $t { $($f: self.$f * rhs),+ }
            }
        }

        impl Mul<$t> for f32 {
            type Output = $t;
            fn mul(self, rhs: $t) -> $t {
                rhs * self
            }
        }

        impl Div<f32> for $t {
            type Output = $t;
            fn div(self, rhs: f32) -> $t {
                $t { $($f: self.$f / rhs),+ }
            }
        }

        impl Neg for $t {
            type Output = $t;
            fn neg(self) -> $t {
                $t { $($f: -self.$f),+ }
            }
        }

        impl AddAssign for $t {
            fn add_assign(&mut self, rhs: $t) {
                *self = *self + rhs;
            }
        }

        impl SubAssign for $t {
            fn sub_assign(&mut self, rhs: $t) {
                *self = *self - rhs;
            }
        }

        impl MulAssign<f32> for $t {
            fn mul_assign(&mut self, rhs: f32) {
                *self = *self * rhs;
            }
        }

        impl DivAssign<f32> for $t {
            fn div_assign(&mut self, rhs: f32) {
                *self = *self / rhs;
            }
        }

        impl Index<usize> for $t {
            type Output = f32;
            /// Component by position.
            ///
            /// # Panics
            ///
            /// Panics when `i` is not a component index.
            fn index(&self, i: usize) -> &f32 {
                let mut k = 0usize;
                $(
                    if i == k {
                        return &self.$f;
                    }
                    k += 1;
                )+
                panic!("index {i} out of range for a {}-component vector", k)
            }
        }

        impl IndexMut<usize> for $t {
            /// Component by position.
            ///
            /// # Panics
            ///
            /// Panics when `i` is not a component index.
            fn index_mut(&mut self, i: usize) -> &mut f32 {
                let mut k = 0usize;
                $(
                    if i == k {
                        return &mut self.$f;
                    }
                    k += 1;
                )+
                panic!("index {i} out of range for a {}-component vector", k)
            }
        }

        impl From<[f32; $n]> for $t {
            fn from(a: [f32; $n]) -> $t {
                $t::from_array(a)
            }
        }

        impl From<$t> for [f32; $n] {
            fn from(v: $t) -> [f32; $n] {
                v.to_array()
            }
        }
    };
}

impl_vector!(Vec2, 2, x, y);
impl_vector!(Vec3, 3, x, y, z);
impl_vector!(Vec4, 4, x, y, z, w);

impl Vec2 {
    /// Unit X.
    pub const X: Vec2 = Vec2::new(1.0, 0.0);
    /// Unit Y.
    pub const Y: Vec2 = Vec2::new(0.0, 1.0);

    /// A vector from its components.
    #[must_use]
    pub const fn new(x: f32, y: f32) -> Vec2 {
        Vec2 { x, y }
    }

    /// Adds a third component.
    #[must_use]
    pub const fn extend(self, z: f32) -> Vec3 {
        Vec3::new(self.x, self.y, z)
    }

    /// The z component of the 3D cross product of `(self, 0)` and
    /// `(rhs, 0)`: positive when `rhs` is counter-clockwise from `self`.
    #[must_use]
    pub fn perp_dot(self, rhs: Vec2) -> f32 {
        self.x * rhs.y - self.y * rhs.x
    }
}

impl Vec3 {
    /// Unit X.
    pub const X: Vec3 = Vec3::new(1.0, 0.0, 0.0);
    /// Unit Y.
    pub const Y: Vec3 = Vec3::new(0.0, 1.0, 0.0);
    /// Unit Z (up in the game's world space).
    pub const Z: Vec3 = Vec3::new(0.0, 0.0, 1.0);

    /// A vector from its components.
    #[must_use]
    pub const fn new(x: f32, y: f32, z: f32) -> Vec3 {
        Vec3 { x, y, z }
    }

    /// The cross product (right-handed: `X.cross(Y) == Z`).
    #[must_use]
    pub fn cross(self, rhs: Vec3) -> Vec3 {
        Vec3::new(
            self.y * rhs.z - self.z * rhs.y,
            self.z * rhs.x - self.x * rhs.z,
            self.x * rhs.y - self.y * rhs.x,
        )
    }

    /// Adds a fourth component (1 for a point, 0 for a direction).
    #[must_use]
    pub const fn extend(self, w: f32) -> Vec4 {
        Vec4::new(self.x, self.y, self.z, w)
    }

    /// Drops the third component.
    #[must_use]
    pub const fn truncate(self) -> Vec2 {
        Vec2::new(self.x, self.y)
    }

    /// Some unit vector perpendicular to `self` (which must be non-zero).
    #[must_use]
    pub fn any_orthonormal(self) -> Vec3 {
        // Cross with the axis least aligned with self, for stability.
        let a = self.abs();
        let axis = if a.x <= a.y && a.x <= a.z {
            Vec3::X
        } else if a.y <= a.z {
            Vec3::Y
        } else {
            Vec3::Z
        };
        self.cross(axis).normalize()
    }
}

impl Vec4 {
    /// Unit X.
    pub const X: Vec4 = Vec4::new(1.0, 0.0, 0.0, 0.0);
    /// Unit Y.
    pub const Y: Vec4 = Vec4::new(0.0, 1.0, 0.0, 0.0);
    /// Unit Z.
    pub const Z: Vec4 = Vec4::new(0.0, 0.0, 1.0, 0.0);
    /// Unit W.
    pub const W: Vec4 = Vec4::new(0.0, 0.0, 0.0, 1.0);

    /// A vector from its components.
    #[must_use]
    pub const fn new(x: f32, y: f32, z: f32, w: f32) -> Vec4 {
        Vec4 { x, y, z, w }
    }

    /// Drops the fourth component.
    #[must_use]
    pub const fn truncate(self) -> Vec3 {
        Vec3::new(self.x, self.y, self.z)
    }
}

// Exact float comparisons below are on values that are exactly
// representable and computed without rounding.
#[cfg(test)]
#[allow(clippy::float_cmp)]
mod tests {
    use super::*;

    #[test]
    fn arithmetic_is_component_wise() {
        let a = Vec3::new(1.0, 2.0, 3.0);
        let b = Vec3::new(4.0, 5.0, 6.0);
        assert_eq!(a + b, Vec3::new(5.0, 7.0, 9.0));
        assert_eq!(b - a, Vec3::splat(3.0));
        assert_eq!(a * b, Vec3::new(4.0, 10.0, 18.0));
        assert_eq!(2.0 * a, a * 2.0);
        assert_eq!(-a, Vec3::new(-1.0, -2.0, -3.0));
        assert_eq!(b / 2.0, Vec3::new(2.0, 2.5, 3.0));
        let mut c = a;
        c += b;
        c -= a;
        c *= 2.0;
        c /= 4.0;
        assert_eq!(c, b / 2.0);
        assert_eq!(a.dot(b), 32.0);
        assert_eq!(a[2], 3.0);
        c[0] = 9.0;
        assert_eq!(c.x, 9.0);
        assert_eq!(<[f32; 3]>::from(a), [1.0, 2.0, 3.0]);
        assert_eq!(Vec4::from([1.0, 2.0, 3.0, 4.0]).truncate(), a);
    }

    #[test]
    fn cross_is_right_handed() {
        assert_eq!(Vec3::X.cross(Vec3::Y), Vec3::Z);
        assert_eq!(Vec3::Y.cross(Vec3::Z), Vec3::X);
        assert_eq!(Vec3::Z.cross(Vec3::X), Vec3::Y);
        assert_eq!(Vec2::X.perp_dot(Vec2::Y), 1.0);
    }

    #[test]
    fn normalisation_edge_cases() {
        assert_eq!(Vec3::new(3.0, 0.0, 4.0).length(), 5.0);
        assert!(Vec3::new(3.0, 0.0, 4.0).normalize().is_normalized(1e-6));
        assert_eq!(Vec3::ZERO.try_normalize(), None);
        assert_eq!(Vec3::ZERO.normalize_or_zero(), Vec3::ZERO);
        assert!(!Vec3::ZERO.normalize().is_finite());
        assert_eq!(Vec2::new(f32::INFINITY, 0.0).try_normalize(), None);
        for v in [Vec3::X, Vec3::new(1.0, 1.0, 1.0), Vec3::new(-0.1, 3.0, 0.2)] {
            let o = v.any_orthonormal();
            assert!(o.is_normalized(1e-6));
            assert!(o.dot(v).abs() < 1e-6);
        }
    }

    #[test]
    #[should_panic(expected = "out of range")]
    fn index_out_of_range_panics() {
        let _ = Vec2::ZERO[2];
    }

    #[test]
    fn lerp_min_max() {
        let a = Vec2::new(0.0, 10.0);
        let b = Vec2::new(10.0, 0.0);
        assert_eq!(a.lerp(b, 0.25), Vec2::new(2.5, 7.5));
        assert_eq!(a.min(b), Vec2::ZERO);
        assert_eq!(a.max(b), Vec2::splat(10.0));
        assert_eq!(
            Vec4::new(-1.0, 2.0, -3.0, 0.0).abs(),
            Vec4::new(1.0, 2.0, 3.0, 0.0)
        );
        assert_eq!(a.distance(b), 200f32.sqrt());
    }
}
