//! Stored-ratio refresh slots: one descriptor per verified member.
//!
//! GENERATED FILE - do not edit by hand (lane `gen2.py`). The descriptor
//! is a name plus an index token; the 32-bit addresses each member was
//! verified with live only in the differential test's case table, never here.

use crate::RatioDesc;

/// One descriptor per verified member, in case-table order.
pub const DESCS: &[RatioDesc] = &[
    RatioDesc { name: "116bfe8", index: 0 },
    RatioDesc { name: "1173354", index: 1 },
    RatioDesc { name: "117358c", index: 2 },
    RatioDesc { name: "1173690", index: 3 },
    RatioDesc { name: "11736a0", index: 4 },
    RatioDesc { name: "1173728", index: 5 },
    RatioDesc { name: "117379c", index: 6 },
    RatioDesc { name: "1175764", index: 7 },
    RatioDesc { name: "1175c54", index: 8 },
    RatioDesc { name: "11764c8", index: 9 },
    RatioDesc { name: "1176870", index: 10 },
    RatioDesc { name: "1176d40", index: 11 },
    RatioDesc { name: "117968c", index: 12 },
    RatioDesc { name: "store_ratio_117e6c4", index: 13 },
    RatioDesc { name: "store_ratio_117e6fc", index: 14 },
    RatioDesc { name: "store_ratio_118d7e4", index: 15 },
    RatioDesc { name: "store_ratio_118debc", index: 16 },
    RatioDesc { name: "store_ratio_118e7dc", index: 17 },
    RatioDesc { name: "store_ratio_118e924", index: 18 },
    RatioDesc { name: "store_ratio_1190e68", index: 19 },
    RatioDesc { name: "f32_ratio_store_1", index: 20 },
    RatioDesc { name: "f32_ratio_store_2", index: 21 },
    RatioDesc { name: "f32_ratio_store_3", index: 22 },
    RatioDesc { name: "f32_ratio_store_4", index: 23 },
    RatioDesc { name: "f32_ratio_store_5", index: 24 },
    RatioDesc { name: "f32_ratio_store_6", index: 25 },
    RatioDesc { name: "f32_ratio_store_7", index: 26 },
    RatioDesc { name: "f32_ratio_store_8", index: 27 },
    RatioDesc { name: "f32_ratio_store_9", index: 28 },
    RatioDesc { name: "screen_aspect_init_00", index: 29 },
    RatioDesc { name: "screen_aspect_init_01", index: 30 },
    RatioDesc { name: "screen_aspect_init_02", index: 31 },
    RatioDesc { name: "screen_aspect_init_03", index: 32 },
    RatioDesc { name: "screen_aspect_init_04", index: 33 },
    RatioDesc { name: "screen_aspect_init_05", index: 34 },
    RatioDesc { name: "screen_aspect_init_06", index: 35 },
    RatioDesc { name: "screen_aspect_init_07", index: 36 },
    RatioDesc { name: "screen_aspect_init_08", index: 37 },
    RatioDesc { name: "screen_aspect_init_09", index: 38 },
    RatioDesc { name: "screen_aspect_init_10", index: 39 },
    RatioDesc { name: "screen_aspect_init_11", index: 40 },
    RatioDesc { name: "screen_aspect_init_12", index: 41 },
    RatioDesc { name: "screen_aspect_init_13", index: 42 },
    RatioDesc { name: "screen_aspect_init_14", index: 43 },
    RatioDesc { name: "screen_aspect_init_15", index: 44 },
    RatioDesc { name: "screen_aspect_init_16", index: 45 },
    RatioDesc { name: "screen_aspect_init_17", index: 46 },
    RatioDesc { name: "screen_aspect_init_18", index: 47 },
    RatioDesc { name: "screen_aspect_init_19", index: 48 },
    RatioDesc { name: "ratio_store_00", index: 49 },
    RatioDesc { name: "ratio_store_01", index: 50 },
    RatioDesc { name: "ratio_store_02", index: 51 },
    RatioDesc { name: "ratio_store_03", index: 52 },
    RatioDesc { name: "ratio_store_04", index: 53 },
    RatioDesc { name: "ratio_store_05", index: 54 },
    RatioDesc { name: "ratio_store_06", index: 55 },
    RatioDesc { name: "ratio_store_07", index: 56 },
    RatioDesc { name: "ratio_store_08", index: 57 },
    RatioDesc { name: "ratio_store_09", index: 58 },
    RatioDesc { name: "ratio_store_10", index: 59 },
    RatioDesc { name: "ratio_store_11", index: 60 },
    RatioDesc { name: "ratio_store_12", index: 61 },
    RatioDesc { name: "ratio_store_13", index: 62 },
    RatioDesc { name: "ratio_store_14", index: 63 },
    RatioDesc { name: "ratio_store_15", index: 64 },
    RatioDesc { name: "ratio_store_16", index: 65 },
    RatioDesc { name: "ratio_store_17", index: 66 },
    RatioDesc { name: "ratio_store_18", index: 67 },
    RatioDesc { name: "ratio_store_19", index: 68 },
];
